### User Login
POST http://localhost:5001/users/login
Content-Type: application/json

{
  "email": "example@gmail.com",
  "password": "password"
}

> {% client.global.set("auth_token", response.body.token); %}

### User Logout
GET http://localhost:5001/users/logout
Authorization: Bearer {{auth_token}}

### Photos List
GET http://localhost:5001/photos/
Authorization: Bearer {{auth_token}}

### Photos Upload
POST http://localhost:5001/photos/upload
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="photo"; filename="photo_1.jpg"

< ./path/to/your/file/photo_1.jpg

### Photos Delete
DELETE http://localhost:5001/photos?id={ObjectID}
Authorization: Bearer {{auth_token}}

### Compliments List
GET http://localhost:5001/compliments?type=for_her
Authorization: Bearer {{auth_token}}

### Random Compliment
GET http://localhost:5001/compliments/random?type=for_her
Authorization: Bearer {{auth_token}}

### Compliments Create
POST http://localhost:5001/compliments
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "type": "for_her",
  "text": "You are the best thing that ever happened to me."
}

### Compliments Delete
DELETE http://localhost:5001/compliments/682495c5e90f825e99e8f9c6
Authorization: Bearer {{auth_token}}

### Drawing Create
POST http://localhost:5001/drawings
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "My Drawing 002",
  "strokeWidth": 5,
  "strokeColor": "123456",
  "drawMode": true,
  "paths": [
    {
      "x": 100,
      "y": 150
    },
    {
      "x": 200,
      "y": 250
    }
  ]
}

### Drawing Short List
GET http://localhost:5001/drawings
Authorization: Bearer {{auth_token}}

### Drawing Get By ID
GET http://localhost:5001/drawings/68372a3283b531aab56e6c27
Authorization: Bearer {{auth_token}}

### Drawing Delete
DELETE http://localhost:5001/drawings/68372a3283b531aab56e6c27
Authorization: Bearer {{auth_token}}

